FROM ubuntu:rolling
MAINTAINER Claudio André (c) 2017-2019 1.0.UbuntuRolling

RUN apt-get update -qq && \
    apt-get install -y \
        build-essential libssl-dev yasm libgmp-dev libpcap-dev pkg-config debhelper libnet1-dev \
        libbz2-dev wget llvm libomp-dev zlib1g-dev git clang \
        libusb-1.0-0-dev && \
    useradd -U -m JtR

# USER JtR => it is much better to use root on Travis
ENV BASE ubuntu
CMD /bin/bash
