name: namebench-snap
version: 1.3.1
confinement: strict
summary: namebench DNS service benchmarking tool
description: Searches the fastest DNS servers available for your computer to use. namebench runs a fair and thorough benchmark using your web browser history, tcpdump output, or standardized datasets in order to provide an individualized recommendation. namebench is completely free and does not modify your system in any way.

apps:
  namebench-snap:
    command: desktop-launch namebench.py
    plugs: [x11, unity7, network, network-bind, browser-support]

  launch:
    command: desktop-launch namebench.py
    plugs: [x11, unity7, network, network-bind, browser-support]

  console:
    command: namebench.py --no_gui
    plugs: [network, network-bind]

parts:
  namebench:
    plugin: python2
    after: [desktop-gtk2]
    source: https://github.com/claudioandre/namebench.git

    stage-packages:
      - tcl
      - blt
      - xdg-utils
      - python-dnspython
      - python-graphy
      - python-jinja2
      - python-simplejson
      - python-tk
      - tk8.6-blt2.5

  viewer:
    plugin: make
    after: [desktop-gtk2]
    source: https://github.com/claudioandre/leve.git
    source-type: git

    build-packages:
      - build-essential
      - libwebkit-dev
      - git

    stage-packages:
      - libwebkitgtk-1.0-0
